netlify/netlify-plugin-lighthouse

- src/lighthouse.js
this prevents the debug module from prefixing a date string to log messages in tty
See https://app.netlify.com/sites/elastic-easley-4ab11f/deploys/5eef41bbc8d60e00074ed78f
> fix(logger): pass colors=true to debug module

- src/index.js
- src/lighthouse.js
Fixes https://github.com/netlify-labs/netlify-plugin-lighthouse/issues/37
See https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md and https://github.com/GoogleChrome/puppeteer/issues/1834
This fixes the issue, but it looks like the `performance` category returns `null` due to the videos in the site.
Tried using `--autoplay-policy=user-gesture-required # Don't render video`  but didn't work.
Seems like a Lighthouse issue.
> Fix: add chrome --disable-dev-shm-usage flag

- .env.example
- .eslintrc.js
- .github/workflows/test.yml
- .gitignore
- README.md
- example/route1/index.html
- example/route2/index.html
- manifest.yml
- netlify.toml
- package.json
- src/config.js
- src/config.test.js
- src/index.js
- yarn.lock
Fixes https://github.com/netlify-labs/netlify-plugin-lighthouse/issues/44
Deprecates `audit_url` for an `audits` list that allows specifying a url/path and thresholds per audit.
~~Still needs some testing and updates to the docs~~
Example:
```toml
[[plugins]]
package = "@netlify/plugin-lighthouse"
[plugins.inputs.thresholds]
performance = 0.9
accessibility = 0.9
best-practices = 0.9
seo = 0.9
pwa = 0.9
[[plugins.inputs.audits]]
path = "route1"
[[plugins.inputs.audits]]
path = "route2"
[[plugins.inputs.audits]]
path = ""
[plugins.inputs.audits.thresholds]
performance = 0.8
```
> feat: support multiple audits urls and paths

- src/lighthouse.js
See before:
https://app.netlify.com/sites/plugin-lighthouse/deploys/5f0c23c7c9f52900075bf9ca
```
12:06:16 PM: Mon, 13 Jul 2020 09:06:16 GMT ChromeLauncher Waiting for browser.
12:06:16 PM: Mon, 13 Jul 2020 09:06:16 GMT ChromeLauncher Waiting for browser...
12:06:16 PM: Mon, 13 Jul 2020 09:06:16 GMT ChromeLauncher Waiting for browser.....
12:06:17 PM: Mon, 13 Jul 2020 09:06:17 GMT ChromeLauncher Waiting for browser.......
12:06:17 PM: Mon, 13 Jul 2020 09:06:17 GMT ChromeLauncher Waiting for browser.......✓
12:06:17 PM: Mon, 13 Jul 2020 09:06:17 GMT config:warn IFrameElements gatherer requested, however no audit requires it.
12:06:17 PM: Mon, 13 Jul 2020 09:06:17 GMT config:warn InspectorIssues gatherer requested, however no audit requires it.
12:06:17 PM: Mon, 13 Jul 2020 09:06:17 GMT …
```
> fix(lighthouse): hide logs timestamp when running in tty

- src/index.js
Fixes https://github.com/netlify-labs/netlify-plugin-lighthouse/issues/46
Prints a detailed version with specific audits to the log, and report a short version (only categories) to be shown in the UI summary.
Build log:
https://app.netlify.com/sites/plugin-lighthouse/deploys/5f184ada44438d0008132480
> feat: list relevant audits on category failure

- src/index.js
Since we're running the Lighthouse audit after the site was built, it makes sense to have it run on `onPostBuild`.
Related to https://github.com/netlify/plugins/issues/134
> fix: use onPostBuild instead of onSuccess

- src/config.js
- src/config.test.js
Fixes https://github.com/netlify-labs/netlify-plugin-lighthouse/issues/79
> fix: report relevant error on invalid jsons

- .github/workflows/release-please.yml
- CONTRIBUTING.md
> chore: add release PR flow

- .github/workflows/test.yml
- package.json
This drops support for Node 10.
This will allow merging https://github.com/netlify-labs/netlify-plugin-lighthouse/pull/134
This will require using `compatibility: { nodeVersion }` in `netlify/plugins.json`.
> chore!: drop support for Node 10

- .github/workflows/test.yml
- netlify.toml
Part of https://github.com/netlify/team-dev/issues/19
This runs the CI on the `latest` Node.js version.
> chore: run CI on latest Node.js

- package-lock.json
- package.json
- src/index.js
This PR resolves [issue](https://github.com/netlify-labs/netlify-plugin-lighthouse/issues/221) in the suggested way.
> However, it seems that, because this plugin relies on puppeteer and http-server, gzip compression is not enabled leading to > a poor performance grade making it unusable for us.
> 
> <img width="744" alt="Screenshot 2021-06-08 at 16 26 33" src="https://user-images.githubusercontent.com/193908/121203659-92d41200-c876-11eb-83b2-2c9af9cc12b5.png">
> 
> <img width="898" alt="Screenshot 2021-06-08 at 16 26 25" src="https://user-images.githubusercontent.com/193908/121203677-96679900-c876-11eb-8273-ec0f15b7573b.png">
Many thanks to @erezrokah for pointing me to that direction. Obviously this is opened to improvements suggestions.
> Fixes #23
> fix: replace http-server by express to enable gzip compression

- README.md
Adding details about the Lighthouse Visualization Labs feature.
> Add Labs visualization details

- .github/workflows/test.yml
- netlify.toml
- package-lock.json
- package.json
This PR does the following:
- Update the node version for building the plugin to v16 since the Netlify system node version was upgraded to 16 recently, see [this post](https://answers.netlify.com/t/build-plugin-update-system-node-js-version-upgrade-to-16/50240).
- Update Lighthouse to v9
- Since this plugin is using Lighthouse v8, which supports Node 12. we are also removing support for Node 12 in the package.json `engines.node` field.
- Update the Node version for CI because the minimum version of Node for Lighthouse v9 is v14. See [this reference.](https://github.com/GoogleChrome/lighthouse/releases/tag/v9.0.0)
These changes should also allow us to unblock the CI build fails for the other PRs and future ones.
We can close this: …
> feat: upgrade Lighthouse and node

- package.json
Since the repository was moved from github.com/netlify-labs/netlify-plugin-lighthouse to https://github.com/netlify/netlify-plugin-lighthouse we need to also update package.json to show the new URL going forward
> chore: update repository url in package.json

- CHANGELOG.md
Updates CHANGELOG.MD:
- Replace all occurrences of `netlify-labs` with `netlify`
- Remove `v3.00` which isn't yet released
- Move `v1.4.2` to the correct section
> fix: update changelog to reflect already released

- .github/workflows/release-please.yml
The working directory defined in the release workflow was an oversight and is not needed
> chore: remove non-existent working directory from workflow

- .github/workflows/test.yml
- netlify.toml
- package-lock.json
- package.json
- Lighthouse v9 does not work with node v18
- This updates the node version in package.json to match anything between v14.15 and 18
- Updated tests to run on v17.9
> fix: specify node version `>=14.15 <18`

- src/index.js
To reduce the processing work to be done for this data, it will be neat to just send what we need. This only affects what we send as part of `extraData`
This basically changes:
```
[
{ title: 'Performance', score: 1, id: 'performance', threshold: 0.5 },
{ title: 'Accessibility', score: 1, id: 'accessibility' },
{ title: 'Best Practices', score: 1, id: 'best-practices' },
{ title: 'SEO', score: 0.91, id: 'seo' },
{ title: 'PWA', score: 0.3, id: 'pwa' }
]
```
to
```json
{   
"performance": 100, "accessibility": 100, "best-practices": 100, "seo": 91,  "pwa": 30 …
```
> feat: reduce summary sent to only id and score

- src/index.js
Fixes an error
```
Cannot read properties of undefined (reading 'reduce')
```
closes https://github.com/netlify/netlify-plugin-lighthouse/issues/450
> fix: account for missing summary

- src/index.js
- src/replacements.js
- src/replacements.test.js
Adds functionality to find/replace snippets of the generated HTML report.
Current functionality added in this PR ensures we _always_ call the existing function which checks for a dark mode preference. The additional code first tests for the existence of a `theme=light` or `theme=dark` query string parameter, falling back to the more standard matchMedia test for dark-mode preference. Switching themes via the navigation dropdown still works as expected.
Risks:
- Relies on the underlying HTML to stay consistent. Will need review between Lighthouse version upgrades.
I'm happy to receive feedback on this approach. It doesn't feel particularly tidy but does functionally work, without introducing a flash of incorrectly themed content which may occur if we were to do a less risky appending of JS …
> feat: inject theme-querying snippets to each report

- src/replacements.js
- src/replacements.test.js
This PR removes the existing (but unused) functionality for reading a users theme preference via query parameter.
Instead, we will use `postMessage` to communicate cross-origin between the report and the App. We'll be sending a theme preference in one direction, and sending back a message when the scroll reaches the page bottom.
This approach has less flexibility than before, in that the theme switching now _only_ works within an iframe (which is fine for current needs). On the plus side, the injection does feel cleaner than the previous iteration as we're now appending a standalone script at the end, rather than injecting mid-function.
> feat: Add support for theme matching and scroll reporting via `postMessage`

- src/index.js
I recently merged a change to add `postMessage` functionality, inserting it in a `<script>`, before the closing `</body>` tag (v3.4.0).
What I didn't notice, is that we run HTML minification _before_ replacements are made, and there was no `</body>` left to match/replace (it is technically valid HTML to not have a closing `</body>` and `</html>`).
This meant the additional `<script>` is not currently being added. I had been testing against a standalone report which had not gone through the minifier. Previous replacements (now removed) had been working fine, as they were matching against strings which happened to not be changed during the process.
This PR moves the `makeReplacements` function call to before the minification, with the bonus effect that the replaced code is now also …
> fix: run replacements function before HTML minification

- README.md
Just a small update here to ensure clarity on auditing multiple site paths and a link to the labs docs.
cc @MetalMatt-Netlify for awareness & review
> Add example showing multiple site paths support in README.md

- src/index.js
Closes https://github.com/netlify/netlify-plugin-lighthouse/issues/441 by adding `Math.round` to the places we normalize the decimal scores to percentages.
This isn't urgent so doesn't need a specific release, it can go out with the next round of changes
> Adds score rounding to avoid floating point errors

- .env.example
- .gitignore
- README.md
- manifest.yml
- src/index.js
- src/lighthouse.js
- src/settings.js
- src/settings.test.js
Closes #387
This PR adds the ability to start passing custom Lighthouse settings, exposing some as optional `netlify.toml` fields.
Example usage (also added to the README):
```
[[plugins]]
package = "@netlify/plugin-lighthouse"
[plugins.inputs.settings]
preset = "desktop" # Optionally run Lighthouse using a desktop configuration
locale = "es" # Any Lighthouse-supported locale, used to generate reports in a different language
```
To start, the `preset` setting allows developers to opt-in to a desktop configuration (which are already set up by Lighthouse).
As a quick-win extra, I've also exposed the `locale` setting. This will allow devs to optionally specify the language used in the generated report. It also affects the reported scores within the Netlify UI. As with all `.toml` settings, …
> Pass (selected) Lighthouse settings via netlify.toml

- src/index.js
This will allow us to detect which version of the Progressive Web App icon to display
> Adds a check for the 'installable-manifest' audit score

- src/index.js
Whenever a score threshold is not met, we fail the build. However, we currently do not send the report data once a threshold fails. This PR aims to fix that by ensuring we always send the report whether the threshold failed or not
tested with this RC build image - https://github.com/netlify/buildbot/pull/2291
Dependent on: https://github.com/netlify/buildbot/pull/2291
fixes https://github.com/netlify/pillar-workflow/issues/731
> feat: send reports on threshold failure

- src/index.js
Whilst implementing accessibility text for the PWA score in App, I noticed "being installable" only depends on one audit, not on multiple like the text description suggests. We're currently checking two – manifest and service worker.
https://github.com/GoogleChrome/lighthouse/blob/main/core/config/default-config.js#L657-L658
The audit grouping confirms having a service worker counts towards being "optimized", but not towards being "installable".
https://github.com/GoogleChrome/lighthouse/blob/main/core/config/default-config.js#L659-L660
This PR reduces the criteria for a report to be classed as installable, hopefully reducing the risk of false negatives
> Reduce scope of 'installable' test

- .github/workflows/test.yml
- package.json
Testing on the (no longer supported) node 17 is blocking our latest Jest upgrade in https://github.com/netlify/netlify-plugin-lighthouse/pull/465
> Jest 29 doesn't support node 17, only 14.15, 16.10, 18+ [source](https://jestjs.io/docs/upgrading-to-jest29#compatibility)
>  As node 17 has passed its official end of life, I'm going to remove it from our workflow in favour of node 18
**Test plan**
Check this PR passes its node 18 tests, and didn't run any node 17 ones :)
> Remove node 17 from test workflow, add node 18

- .github/CODEOWNERS
- renovate.json
Narrows the CODEOWNDERS scope to a single pod
Adds the following renovate options (borrowed from elsewhere in the Netlify Org):
- `schedule` – now runs at 9am on Fridays to add predictability
- `labels` – tags the PR as a dependency update
- `stabilityDays` – only bumps to a new version once it's been public for at least 3 days (avoids any immediate bugs, and matches the npm cutoff for removing a version)
- `prCreation` – Don't create PRs until all status checks have completed
> Update Renovate config and CODEOWNERS

- README.md
- fixed fragment links in the introduction
- moved detailed audit config to right after custom audits are introduced
- dropped a single control character (previous line 97)
> fix(docs): fix broken links and content flow

- package-lock.json
- src/index.js
When testing the plugin locally, I've started getting 403 responses:
```
'Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403)'
```
Turns out macOS uses port 5000 for Airplay. We should use a different one!
---
Googling tells me we can reclaim 5000 by disabling this system prefs option,  but as I've never used this, I'm guessing "on" is the default choice.
> Change localhost port to avoid macOS collision

- package-lock.json
- package.json
Closes https://github.com/netlify/netlify-plugin-lighthouse/issues/510
Originally, [the upgrade to Puppeteer 19.x was failing](https://github.com/netlify/netlify-plugin-lighthouse/pull/499), and their docs advised `createBrowserFetcher` was to be deprecated, which is why we paused renovate updating this dependency.
Now, however, it seems the issue we were seeing with a change to the args for `createBrowserFetcher` has been resolved, and their docs have been updated to state `createBrowserFetcher` is [deprecated only for users of `puppeteer-core`](https://pptr.dev/api/puppeteer.puppeteernode.createbrowserfetcher/) (not us)
TL;DR a minor version bump on their side has already fixed the issues, and we no longer have a deprecation to worry about 🎉 
Cypress specs are passing, and I've tested …
> fix(deps) Upgrade puppeteer to v 19.5.2

- package-lock.json
- package.json
- src/index.js
Closes https://github.com/netlify/netlify-plugin-lighthouse/issues/510
Upgrades puppeteer, working around the new caching behaviour by making sure the puppeteer cache is saved/restored on each build.
Internal test steps:
- Check running the plugin locally continues to work as expected across multiple test runs
- [This test site](https://app.netlify.com/sites/lighthouse-testing-ii) is using this branch's version of the plugin - retrying deploys (without any cache clearing) should result in lighthouse scores being generated consistently
> fix(deps): Upgrade puppeteer using cache utils

- package-lock.json
- package.json
- src/index.js
This reverts commit f831eb1ead7e0705e432ea5d7c6b1168a5db83c6.
Issues with this commits dependency changes were raised in https://github.com/netlify/netlify-plugin-lighthouse/issues/543
> Revert "fix(deps): Upgrade puppeteer using cache utils (#540)"

- jest.config.cjs
- package-lock.json
- package.json
- src/lib/get-serve-path/get-serve-path.test.js
- src/lib/get-server/get-server.test.js
This adds the jest coverage report when we run the tests locally, and adds a couple of new specs (bringing coverage for those particular files up to 100).
This contributes to internal tracking issue https://github.com/netlify/pillar-workflow/issues/1059 (but there's still more to do!)
> Add some additional specs and set up jest coverage

- README.md
Fixes the first example in the README, which has an incorrect sub-table array name - `[plugins.inputs]` instead of `[plugins.inputs.audits]` - that can lead to issues processing `netlify.toml` e.g. any header definitions in the file won't get parsed. 
Anyone copypasta-ing this first example (like, er, me) would likely end up with issues in their config.
The other examples in README look good; just the first that has issues.
Using the version from the README with no changes:
```toml
[[plugins]]
package = "@netlify/plugin-lighthouse"
[plugins.inputs.thresholds]
performance = 0.9
accessibility = 0.9
best-practices = 0.9
seo = 0.9
pwa = 0.9
[plugins.inputs]
output_path = "reports/lighthouse.html"
```
...gives a log that look something like this:
```
8:32:16 PM: Starting post processing …
```
> docs: fix audits sub-table array name

- CONTRIBUTING.md
Adds notes on chromium download workaround for M1 Macs to the contributing doc
> add chromium install for m1 notes to contributing.md

- .github/workflows/test.yml
- package-lock.json
- package.json
- src/lib/get-configuration/get-configuration.test.js
This PR adds support for the current version of NodeJS (node 19).
The last "odd" version of NodeJS (17) was also supported and I think I'm not the only one that uses "current" NodeJS for development.
As far as I can tell NodeJS 19 works perfrectly fine with this plugin.
> Add node 19.x to the test matrix to support the current node version

- src/lighthouse.js
This code was introduced to suppress duplicate dates in the Deploy Log. Now we are using a quieter output style, we don't need this logic.
- Introduced: https://github.com/netlify/netlify-plugin-lighthouse/pull/50
- Updated: https://github.com/netlify/netlify-plugin-lighthouse/pull/51 
It had actually stopped working at some point anyway… [leading to this issue](https://github.com/netlify/pillar-workflow/issues/862) which we can also close.
This change should have no effect on the plugin functionality
> Remove obsolete DEBUG_COLORS logic

- package.json
- src/index.js
- src/index.test.js
(went for a long PR title just for the sake of the changelog since we're going to cut a release with this)
Renames the env var to run on success to make this ready for experimental use.
Steps to validate:
- Using the plugin version at this branch, run a deploy for a site without adding any env variables/inputs for `run_on_success`. Plugin should run `onPostBuild` as before
- Set `run_on_success` to `'true'` in the site's `toml` file and deploy. Plugin should run on success and results should be shown in the UI when ready
- Remove the toml setting and set an environment variable for your site `LIGHTHOUSE_RUN_ON_SUCCESS='TRUE'`. Plugin should run on success and results should be shown in the UI when ready
> feat: Allow plugin to run onSuccess with toml setting or env var LIGHTHOUSE_RUN_ON_SUCCESS

- src/lib/run-audit-with-server/index.js
- src/lighthouse.js
Fixes #548 
This was kind of a weird one to investigate. Initially after having set some additional error logging, I noticed this output:
```
1:19:22 PM: Error: Could not find local browser
1:19:22 PM:     at getBrowserPath (file:///opt/build/repo/node_modules/@netlify/plugin-lighthouse/src/lighthouse.js:10:11)
1:19:22 PM:     at async runAuditWithServer (file:///opt/build/repo/node_modules/@netlify/plugin-lighthouse/src/lib/run-audit-with-server/index.js:19:25)
1:19:22 PM:     at async runEvent (file:///opt/build/repo/node_modules/@netlify/plugin-lighthouse/src/lib/run-event/index.js:73:9)
1:19:22 PM:     at async onPostBuild (file:///opt/build/repo/node_modules/@netlify/plugin-lighthouse/src/index.js:37:9)
1:19:22 PM:     at async Object.run …
```
> fix: Fix chrome-launcher error preventing reports being generated

- README.md
- manifest.yml
- netlify.toml
- package-lock.json
- package.json
- src/e2e/fail-threshold-onpostbuild.test.js
- src/e2e/fail-threshold-onsuccess.test.js
- src/e2e/lib/reset-env.js
- src/e2e/not-found-onpostbuild.test.js
- src/e2e/not-found-onsuccess.test.js
- src/e2e/settings-locale.test.js
- src/e2e/settings-preset.test.js
- src/e2e/success-onpostbuild.test.js
- src/e2e/success-onsuccess.test.js
- src/index.js
- src/index.test.js
Closes #587 
We previous released the ability to run the plugin during the `onSuccess` build step as experimental/undocumented functionality. We've had good feedback from users and are now ready to roll this out as the default behaviour.
**⚠️ This PR has breaking changes**
The plugin will now run _after_ a deploy has completed auditing the live deploy rather than the statically served build folder. This will:
- Allow the plugin to be used on ISR/SSR sites
- Speed up "time to deploy" since the plugin run no longer holds up the deploy
- Allow the plugin to run in an environment truer to production
The main side effect of this change is that if score thresholds have been configured, **the plugin will no longer fail the deploy if those scores are not met**. 
To continue running the plugin …
> feat!: Run plugin on live deploy URL by default 

- src/lib/get-settings/get-settings.test.js
- src/lib/get-settings/index.js
- src/lib/run-audit-with-url/index.js
- src/lib/run-event/index.js
When we run onSuccess we use the `DEPLOY_URL` i.e. the permalink of the deploy. These deploys have `x-robots-tag: noindex` configured to stop bots from crawling deploy permalinks vs the main production site URL. This means we almost always receive a false positive for the lighthouse `is-crawlable` rule.
This PR skips that particular audit when running against the deploy url.
**To test:**
- You could install the branch version of this plugin on a site and observe the difference in behaviour, but I did prepare an example 😄 
- [This deploy is made with the latest fix](https://app.netlify.com/sites/suzanne-lighthouse-test/deploys/6716572fb3a7510009cc7902) - observe that the SEO report does not include any failure for allowing crawling
- [This deploy was made before the …
> fix: skip is-crawlable audit when running onSuccess against DEPLOY_URL
